### ISSUE TITLE
turn server

### ISSUE THREAD

**Issue by dotnethii** [AMEST/PeerMeeting#18]
very very good .Thanks

**Comment by AMEST** [comment]
working on bugs

**Comment by AMEST** [comment]
Added support for Coturn server TURN to the application.
This feature is already enabled on the site and it should work. (added a small knob to enable only TURN mode if there are problems with connecting via stun and do not want to wait until the choice comes to using the turn protocol (and also for testing). To do this, enter `window.localStorage.turnOnly in the browser console = JSON.stringify (false)`.)
In the documentation, I added information that is needed to deploy the service on your own.
